version: '3'

services:
  tokenlab-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "tokenlabkalendar"
    ports:
      - "15432:5432"
    volumes:
      - /home/adrian/IdeaProjects/tokenlab-calendar/.mydocker/postgresql/:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  tokenlab-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "adriantodt.ms@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "tokenlabkalendar"
    ports:
      - "16543:80"
    depends_on:
      - tokenlab-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
